### ISSUE TITLE
Does not work with flake8 version 6

### ISSUE THREAD

**Issue by Aspect26** [bagerard/flake8-test-name#9]
I have flake8 on version 6.1.0, flake8-test-name version 0.1.5 and get the following error:

```
flake8 ./app/src/

Traceback (most recent call last):
  File "/XXX/venv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/XXX/venv/lib/python3.10/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/XXX/venv/lib/python3.10/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/XXX/venv/lib/python3.10/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/XXX/venv/lib/python3.10/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
  File "/XXX/venv/lib/python3.10/site-packages/flake8/options/parse_args.py", line 51, in parse_args
    option_manager.register_plugins(plugins)
  File "/XXX/venv/lib/python3.10/site-packages/flake8/options/manager.py", line 259, in register_plugins
    add_options(self)
  File "/XXX/venv/lib/python3.10/site-packages/flake8_test_name.py", line 76, in add_options
    option_manager.add_option(
  File "/XXX/venv/lib/python3.10/site-packages/flake8/options/manager.py", line 281, in add_option
    self._current_group.add_argument(*option_args, **option_kwargs)
  File "/usr/local/lib/python3.10/argparse.py", line 1435, in add_argument
    raise ValueError('%r is not callable' % (type_func,))
ValueError: 'str' is not callable
```

**Comment by bagerard** [comment]
Thanks for reporting, I'll have a look

**Comment by bagerard** [comment]
0.1.6 was released with the fix

**Comment by Aspect26** [comment]
great! thank you very much! :)
